#!/bin/sh
### BEGIN INIT INFO
# Provides:          dzen2
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Dzen2 status bar
### END INIT INFO

DAEMON=/home/SEU_USUARIO/.config/dzen2/status.sh
NAME=dzen2
PIDFILE=/var/run/$NAME.pid

case "$1" in
  start)
    echo "Iniciando $NAME..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
    ;;
  stop)
    echo "Parando $NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 5
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE) 2>/dev/null; then
      echo "$NAME está rodando (PID $(cat $PIDFILE))"
    else
      echo "$NAME não está rodando"
      exit 1
    fi
    ;;
  *)
    echo "Uso: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
